<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>Fix1603</AssemblyName>
    <RootNamespace>Fix1603</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyTitle>Autodesk 1603 错误修复工具</AssemblyTitle>
    <Product>Fix1603</Product>
    <Version>1.0.0</Version>
    <Company>Qianxun</Company>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.ServiceProcess" />
  </ItemGroup>

</Project>
